# Generated by Django 3.1.4 on 2021-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_apidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='subscribtionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
