# Generated by Django 3.1.4 on 2021-07-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210717_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
