# Generated by Django 3.1.4 on 2021-09-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_apidata_subscribtiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='subscribtionID',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
