# Generated by Django 3.1.4 on 2021-09-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_apidata_subscribtionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidata',
            old_name='subscribtionID',
            new_name='subscriptionID',
        ),
    ]
