# Generated by Django 4.0.6 on 2022-07-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_apidata_verificationsecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entryIDs', models.JSONField(default=list)),
                ('lastChanged', models.DateTimeField()),
            ],
        ),
    ]
